name: symbol_ddk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  base32: ^2.1.3
  big_decimal: ^0.5.0
  convert: ^3.1.1
  file_saver: ^0.2.8
  http: ^1.1.0
  logger: ^2.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
